services:
  db:
    container_name: "db"
    image: postgres:latest
    env_file:
      - .env
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:
